name: kopicarlo

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kopicarlo_backend_app  # ✅ Make sure this is correct
    dns: 8.8.8.8
    ports:
      - "8000:8000"
    environment:
      - HOST=192.168.6.87
      - PORT=8000
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=kopicarlo
      - DB_NAME=kopicarlo_db
      - X_API_KEY=e6a637643ca02f19580e14895664d470
      - CONS_ID=39205596
    depends_on:
      db:
        condition: service_healthy
    networks:
      - kopicarlo_network
    restart: always

  db:
    image: docker.io/library/mysql:8.0
    container_name: mysql_container_kopicarlo
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: kopicarlo
      MYSQL_DATABASE: kopicarlo_db
    volumes:
      - mysql_data_kopicarlo:/var/lib/mysql
    networks:
      - kopicarlo_network
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --password=secret || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: docker.io/library/redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  phpmyadmin:
    image: docker.io/phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container_kopicarlo
    ports:
      - "8082:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: kopicarlo
    depends_on:
      - db
    networks:
      - kopicarlo_network
    restart: always

networks:
  kopicarlo_network:
    driver: bridge

volumes:
  mysql_data_kopicarlo:
  redis_data:
