version: "3.8"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kopicarlo_frontend_app
    ports:
      - "4000:4000"
    dns:
      - 8.8.8.8
    environment:
      NEXT_PUBLIC_API_HOST: "192.168.6.87"
      NEXT_PUBLIC_API_PORT: "8000"
      NEXT_PUBLIC_API_PORT_FE: "4000"
      PASSWORD: "e6a637643ca02f19580e14895664d470"
      CONSUMER_ID: "39205596"
      NEXT_PUBLIC_BACKEND_HOST: "http://192.168.6.87:5000"
      URL_DEFAULT: "http://139.255.24.122/medapp-v2/public/"
      RS_ID: "21119"
      API_ERSSC: "http://192.168.6.86/api/"
      CONS_ID_FARMASI: "21011919"
      BASE_URL: "http://139.255.24.122:8080/"
      URL_GOOGLE: "https://app-medapp.eksad.com"
      API_BASE_URL_PROD: "https://app-medapp.eksad.com/medapp-v2/medapp/api/"
      TOKEN: "d6d4685417ef2287424ffda3b0f88746"
    networks:
      - kopicarlo_fe_network
    stdin_open: true
    tty: true
    restart: always
    command: ["npx", "next", "start", "-p", "4000", "-H", "0.0.0.0"]

networks:
  kopicarlo_fe_network:
    driver: bridge
